### PR TITLE
Fix the listener,py and enable multi camera. 

### PR DESCRIPTION
**Pull request by MikoyChinese**
1. Fix realsense listener.py and enable multi realsense.
2. Add realsense serial_no to detect_yolo launch file.
3. Fix if the depth value unvailed, so the object tracking point will create in camera coordinate.

### CODE REVIEW

**Comment by jefft0** [comment]
Hello @MikoyChinese . Can you update the Dockerfile in your branch to be the same as the dev branch on [lines 36 and 37](https://github.com/OpenPTrack/open_ptrack_v2/blob/d67cd1f76409788ff779e52d1d528582f85a61a6/docker/open_ptrack-dep/Dockerfile#L36) ? This will make your pull request not conflict with the current dev branch.

    RUN  sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'     \ 
        && apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654     \

**Comment by bsubbaraman** [comment]
Hi @MikoyChinese , thanks for the updates to listenery.py and calibration_initializer.py.  We don’t need other unrelated commits.  Can you update the pull request so that it is only has these changes?

**Comment by MikoyChinese** [comment]
Hi @bsubbaraman, @jefft0,
Yes, I will do it. Sorry about that I modified the other files just met my demand.
And I will update some commits for fixing some bugs I found. And I will show you the reason.

1. Update the **listener.py and calibration_initializer.py** for multi-realsense camera and adjust the witdth and height you need.
2. Fix **yolo_based_object_detector_node.cpp** and Change the following line to `if (medianDepth <= 0 || medianDepth > 6.25)`. Because I found that if the sensor return 0(which are the black points in the depth image.), it will made the tracking coordinate became the coordinate of sensor.(x = x * depth, y = y * depth, if depth = 0, the (x, y) -> (0, 0), that is no sense.)
 https://github.com/OpenPTrack/open_ptrack_v2/blob/c7721626c017bf01431131f68e9db1cbf4393170/yolo_detector/src/yolo_based_object_detector_node.cpp#L238
3. I will update the **realsense_frames.launch** and change name to `$(arg camera)_broadcaster`. For the reason that if it has more than 2 sensor need transform_publisher, it will get errors. https://github.com/OpenPTrack/open_ptrack_v2/blob/c7721626c017bf01431131f68e9db1cbf4393170/detection/launch/realsense_frames.launch#L8
4. Fix **yolo_based_object_detector_node.cpp** for free the some object no need. I will append two lines `free(boxes->boxes) free(boxes)`, because if you don't free it, it will always occupy the memory until the pc collapses.
https://github.com/OpenPTrack/open_ptrack_v2/blob/c7721626c017bf01431131f68e9db1cbf4393170/yolo_detector/src/yolo_based_object_detector_node.cpp#L316

**Comment by bsubbaraman** [comment]
Thanks for the reply, @MikoyChinese - these all seems like good and much appreciated changes!

**Pull request closed without merging**
