### PR TITLE
Support multiple sensors

### PR DESCRIPTION
**Pull request by JimZhou-001**
Support multiple sensors

### CODE REVIEW

**Comment by jefft0** [comment]
Should I merge these changes into branch 1804, to keep it up to date?

**Comment by JimZhou-001** [comment]
@jefft0 I tested on Ubuntu 16.04. Parameter "sensor" determines which (Kinect 2.0) camera it listens to. Maybe 1804 is the same.

**Comment by jefft0** [comment]
OK. Sounds like it's pretty straight-forward and I should merge these changes into 1804.
@bsubbaraman and @SimeonOA , what do you think?

**Comment by SimeonOA** [comment]
It seems alright to me as well.

Thank you.

**Comment by bsubbaraman** [comment]
Seems good to me as well, @jefft0

**Comment by jefft0** [comment]
This pull request is to merge into dev. Shouldn't it merge into master?

**Comment by jefft0** [comment]
Maybe I spoke too soon. I see "JimZhou-001 changed the base branch from master to dev 5 days ago". I'm confused. Are we putting changed in dev or master?

**Comment by jefft0** [comment]
I merged these changes into branch 1804 in pull request #86.

**Comment by JimZhou-001** [comment]
@jefft0 Sorry, I'm not familiar with these oprations. And thank you for agreeing my request.

**Comment by jefft0** [comment]
No problem. My idea was to merge to branch 1804 in addition to master. @bsubbaraman, do you still want to merge this to master (for Ubuntu 16.04)?

**Comment by jburkeucla** [comment]
@jefft0 there is a need for this in an installation at Harvard.  If no objections, let's merge into 16.04 as well and have @bsubbaraman generate a new docker image for that as well.

**Comment by jburkeucla** [comment]
Update: the patch was tested manually at Harvard and works.

**Pull request merged**
