### PR TITLE
Fox

### PR DESCRIPTION
**Pull request by MikoyChinese**
@Issue: https://github.com/OpenPTrack/open_ptrack_v2/pull/53#issuecomment-513060468

1. Update the **listener.py and calibration_initializer.py** for multi-realsense camera and adjust the witdth and height you need.
2. Fix **yolo_based_object_detector_node.cpp** and Change the following line to `if (medianDepth <= 0 || medianDepth > 6.25)`. Because I found that if the sensor return 0(which are the black points in the depth image.), it will made the tracking coordinate became the coordinate of sensor.(x = x * depth, y = y * depth, if depth = 0, the (x, y) -> (0, 0), that is no sense.)
 https://github.com/OpenPTrack/open_ptrack_v2/blob/c7721626c017bf01431131f68e9db1cbf4393170/yolo_detector/src/yolo_based_object_detector_node.cpp#L238
3. I will update the **realsense_frames.launch** and change name to `$(arg camera)_broadcaster`. For the reason that if it has more than 2 sensor need transform_publisher, it will get errors. https://github.com/OpenPTrack/open_ptrack_v2/blob/c7721626c017bf01431131f68e9db1cbf4393170/detection/launch/realsense_frames.launch#L8
4. Fix **yolo_based_object_detector_node.cpp** for free the some object no need. I will append two lines `free(boxes->boxes) free(boxes)`, because if you don't free it, it will always occupy the memory until the pc collapses.
https://github.com/OpenPTrack/open_ptrack_v2/blob/c7721626c017bf01431131f68e9db1cbf4393170/yolo_detector/src/yolo_based_object_detector_node.cpp#L316

### CODE REVIEW

**Comment by bsubbaraman** [comment]
Hi @MikoyChinese,

When running multi-camera RealSense and adding my RealSense serial number to my `ros_network.env` file,  I get the following error:
`arg 'sensor_id' is not defined. 

Arg xml is <arg name="serial_no" value="$(arg sensor_id)"/>
The traceback for the exception was written to the log file`

I believe this is because your change to the `calibration_initializer.py` file should be `sensor_msg.serial = sensor_item['serial']` instead of `sensor_msg.id_num = sensor_item['serial']`, since subsequent checks in `listener.py` check for a serial number, not for an id number.  Does this seem right to you?

When I make this change I can launch multi-camera tracking, but I then get the following error message in my detection node: `[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!`
This is while running just person detection (pose and object detection are set to false).  Do you also get this error?  If so, do you know which of your changes causes this error?  If not, could you describe your steps to launch OpenPTrack?

Thank you!

**Comment by MikoyChinese** [comment]
`sensor_msg.id_num = sensor_item['serial']` is right.
But the error `[pcl::OrganizedNeighbor::radiusSearch] Input dataset is not from a projective device!` I never got. Maybe you should me the `detection_node_xx.launch`, `detector_realsense.launch` or try to run `rostopic echo /xx/depth_registered/points` for checking the sensor's depth is ok.

**Comment by bsubbaraman** [comment]
Thanks for the reply, @MikoyChinese .  I tracked down the problem to be with the width and height that you pass through in `listenery.py`; when I comment out those lines, everything works as expected.  I am using a RealSense D435.  Are you using a different model?  Are you sure about the values width=424, height=240?  Thanks for your help!

**Comment by MikoyChinese** [comment]
@bsubbaraman You are so nice.
**Answer:**
1. The values width=424, height=240 are no problem in my enviorment, my sensor is also Realsense D435 and run this project in docker. And if you install the [librealsense2 SDK](https://github.com/IntelRealSense/librealsense), you can run the cmd `realsense-viewer` to check your sensor resolution ratio which will list all available resolution and include 424x240. But for avoiding this case, I will change to 640x480.
2. The end tag of the include statement is wrong, it will be change next committing.
3. In `skeleton_detector_realsense.launch`, arg `sensor_id` has no usefulness. I think it maybe should be removed.

**Comment by bsubbaraman** [comment]
Thanks for the changes, @MikoyChinese.  You're right that `sensor_id` is currently not used in `skeleton_detector_realsense.launch`; I'll look into that, but for now it might be easier to change `sensor_id` to `serial_no` in `skeleton_detector_realsense.launch` in case it has some use in the future.

**Pull request merged**
