### PR TITLE
fixed frame_ids not matched bug

### PR DESCRIPTION
**Pull request by Tobix99**
Hey,
I found a bug in the face detection, where the sensorname was e.g. "/kinect02"

and the compare did compare the frame_id --> which was kinect02 without the slash

so I added a slash for the compare

### CODE REVIEW

**Comment by Tobix99** [comment]
weird, at other camera, other frame ID is checked(rgb not ir), but leading slash is also missing

**Comment by samamin** [comment]
I made a few other changes related to this bug on the machine in the LT, will pull what I did and compare this week.

**Comment by jburkeucla** [comment]
@bsubbaraman please test and review.

**Comment by jefft0** [comment]
Also would need to merge to 1804 branch.

**Pull request merged**
